---
- name: upadte system
  apt:
    update_cache: yes
    cache_valid_time: 86400
    
- name: install dependancy
  apt:
    name: "{{ item }}"
    state: present
  loop:
   - libtiff-dev
   - libjpeg-dev
   - zlib1g-dev
   - libfreetype6-dev
   - liblcms2-dev
   - libwebp-dev
   - tcl-dev 
   - tk-dev
   - python-tk
   - python-dev
   - libpq-dev
   - python3-pip
   - python3-virtualenv
   - nginx
   
- name: install uwsgi and Django
  pip:
    name: 
     - uwsgi
     - Django
     - psycopg2

- name: check is file exists
  stat:
    path: /home/ubuntu/uwsgi-tutorial
  register: stat_result
     
- name: create virtualenv
  shell: |
    virtualenv /home/ubuntu/uwsgi-tutorial
    cd /home/ubuntu/uwsgi-tutorial
    source bin/activate
    django-admin.py startproject mysite
  when: not stat_result.stat.exists

- name: folders
  file:
    path: "/home/ubuntu/uwsgi-tutorial/mysite/{{ item }}"
    state: directory
  loop:
    - media
    - static
    
- name: copy nginx conf
  copy:
    src: ../files/mysite_nginx.conf
    dest: /etc/nginx/conf.d/mysite_nginx.conf
    
- name: copy uwsgi params
  copy: 
    src: ../files/uwsgi_params
    dest: /home/ubuntu/uwsgi-tutorial/mysite/uwsgi_params

- name: copy uwsgi params
  copy: 
    src: ../files/mysite_uwsgi.ini
    dest: /home/ubuntu/uwsgi-tutorial/mysite/mysite_uwsgi.ini

- name: config setting.py
  template:
    src: setting.j2
    dest: /home/ubuntu/uwsgi-tutorial/mysite/mysite/settings.py
      
- name: check is file exists
  stat:
    path: /home/ubuntu/uwsgi-tutorial/mysite/static/admin
  register: is_colect
  
- name: collectstatistic
  shell: |
    cd /home/ubuntu/uwsgi-tutorial/mysite
    python3 manage.py collectstatic
  when: not is_colect.stat.exists
    
- name: restart nginx
  service: 
    name: nginx
    state: restarted
    enabled: yes   

- name: add rc.local
  copy: 
    src: ../files/rc.local
    dest: /etc/rc.local
    
- name: add +x
  file:
    dest: /etc/rc.local
    mode: a+x
      
- name: reboot
  reboot:
