---
- name: upadte system
  apt:
    update_cache: yes
    cache_valid_time: 86400
    
- name: install dependancy
  apt:
    name: "{{ item }}"
    state: present
  loop:
   - libtiff-dev
   - libjpeg-dev
   - zlib1g-dev
   - libfreetype6-dev
   - liblcms2-dev
   - libwebp-dev
   - tcl-dev 
   - tk-dev
   - python-tk
   - python-dev
   - libpq-dev
   - python3-pip
   - python-setuptools
   - python3-virtualenv
   - nginx
   
- name: install uwsgi and Django
  pip:
    name: 
     - uwsgi
     - Django
     - psycopg2

- name: check is file exists
  stat:
    path: "{{ env_path }}"
  register: stat_result
     
- name: create virtualenv
  shell: |
    virtualenv {{ env_path }}
    cd {{ env_path }}
    source bin/activate
    django-admin.py startproject {{ project_name }}
  when: not stat_result.stat.exists

- name: folders
  file:
    path: "{{ project_path }}/{{ item }}"
    state: directory
  loop:
    - media
    - static
    
- name: copy nginx conf
  template:
    src: mysite_nginx.j2
    dest: /etc/nginx/nginx.conf
    
- name: copy uwsgi params
  copy: 
    src: ../files/uwsgi_params
    dest: "{{ project_path }}/uwsgi_params"

- name: copy mysite_uwsgi.ini
  template: 
    src: mysite_uwsgi.ini.j2
    dest: "{{ project_path }}/{{ project_name }}_uwsgi.ini"

- name: config setting.py
  template:
    src: setting.j2
    dest: "{{ project_path }}/{{ project_name }}/settings.py"
      
- name: check is file exists
  stat:
    path: "{{ project_path }}/static/admin"
  register: is_colect
  
- name: collectstatistic
  shell: |
    cd {{ project_path }}
    python3 manage.py collectstatic
    python3 manage.py migrate
  when: not is_colect.stat.exists
  notify: add user
    
- name: restart nginx
  service: 
    name: nginx
    state: restarted
    enabled: yes   

- name: add rc.local
  template: 
    src: rc.local.j2
    dest: /etc/rc.local
    
- name: add +x
  file:
    dest: /etc/rc.local
    mode: a+x
      
- name: reboot
  reboot:
