- hosts: localhost
  become: false
  
  tasks:
    - name: Define the backend configuration at init
      community.general.terraform:
        project_path: "../terraform"
        state: present
        force_init: true
        backend_config:
          region: "eu-west-3"
          bucket: "tr-bucket-kr"
          key: "terraform.tfstate"
      register: out
    - debug: var=out.outputs

- name: reboot
  hosts: aws_ec2
  become: true
  roles:
    - role: django
